name: Run Cypress Tests

# Controls when the action will run
on:
  push:
    branches:
      - master   # run on master branch push
  pull_request:
    branches:
      - master   # run on pull requests targeting master branch

# Define the jobs
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Adjust as needed

    strategy:
      matrix:
        browser: [chrome]  # Run tests in Chrome

    steps:
    # Step 1: Start Ubuntu and Install Dependencies
    - name: Set up Ubuntu environment
      run: sudo apt-get update && sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev build-essential xvfb

    # Step 2: Install Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Specify the version of Node.js

    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
         fetch-depth: 0  # Fetch all history to avoid shallow clone issues
         submodules: true  # If you use submodules, this will ensure they are fetched
    
    # Step 2: Debug the current working directory and list files
    - name: Show Current Directory and Files
      run: |
        pwd     # Show the current working directory
        ls -la  # List all files to check for missing ones
     
    # Step 3: Install project dependencies
    # - name: Install Dependencies
    #   run: |
    #     cd ..
    #     npm install

    # Step 4: Cache Cypress binary
    - name: Cache Cypress binary
      uses: actions/cache@v3
      with:
        path: ~/.cache/Cypress
        key: ${{ runner.os }}-cypress-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-cypress-
          
    # Step 4: Cache Node.js modules
    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    # Step 5: Install Cypress dependencies
    - name: Install Cypress dependencies
      run: |
        sudo apt-get install -y libnss3 libgconf-2-4
        sudo apt-get install -y google-chrome-stable
        npm install cypress
        npx cypress install  # Ensure Cypress binary is installed

    # Set Cypress executable permissions
    - name: Set Cypress executable permissions
      run: |
        chmod +x ./node_modules/.bin/cypress

    # Step 6: Run Cypress Tests
    - name: Run Cypress Tests on ${{ matrix.browser }}
      run: |
        ls
        npx cypress run --browser ${{ matrix.browser }}

    # Step 7: Upload test reports
    - name: Upload Cypress Report
      uses: actions/upload-artifact@v3
      with:
        name: cypress-report
        path: cypress/reports

    # Step 8: Save screenshots and videos
    - name: Upload Cypress Screenshots and Videos
      uses: actions/upload-artifact@v3
      with:
        name: cypress-artifacts
        path: cypress/screenshots,cypress/videos